steps:
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.11'

  - name: Ensure pip is installed
    run: |
      python -m ensurepip --upgrade
      python -m pip --version

  - name: Upgrade pip
    run: python -m pip install --upgrade pip

  - name: Install dependencies
    run: python -m pip install -r requirements.txt
