name: Train LSTM Model

on:
  push:
    branches:
      - master

jobs:
  train:
    runs-on: self-hosted  # Utiliza un runner auto-hospedad

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set UTF-8 Encoding
        run: |
          chcp 65001
        shell: cmd

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Ensure pip is installed
        run: |
          python -m ensurepip --upgrade
          python -m pip --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
        env:
          PYTHONIOENCODING: utf-8

      - name: Verify Tcl/Tk Installation
        run: |
          python -m tkinter || echo "Tcl/Tk is not required for headless execution."

      - name: Train LSTM Model
        run: |
          python train.py
        env:
          PYTHONIOENCODING: utf-8

      - name: Upload Predictions Plot
        uses: actions/upload-artifact@v3
        with:
          name: predictions
          path: predicciones.png

      - name: Finalize
        run: |
          echo "Training completed successfully."
